name: 定时检查更新

# 控制何时运行工作流
on:
  # 在push或者pull请求事件触发工作流，但只对"main"分支有效
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 允许你在Actions标签手动运行此工作流
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 这段表示工作流将在每天的零点运行，也就是每24小时一次
# 工作流运行由一个或多个可以顺序或并行的工作组成
jobs:
  # 这个工作流包含一个名为 "构建" 的单一工作
  build:
    # 工作将会在哪个类型的运行环境下运行
    runs-on: ubuntu-latest

    # 阶段代表的是作为工作部分将要执行的一系列任务
    steps:
      # 在$GITHUB_WORKSPACE下检出你的库，以便你的工作可以访问
      - uses: actions/checkout@v3

      # 使用运行环境的shell运行单个命令
      - name: 下载和修改文件
        run: |
          curl -o 免费机场-付费机场 'https://api1.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=8325e7673530ce15cad8e1d915658cec&flag=clashmeta'
          sed -i 's/down: 100/down: 400/g' 免费机场-付费机场
  
      - name: 提交和推送
        run: |
          git config --local user.email "action@site.com"
          git config --local user.name "GitHub Action"
          git add 免费机场-付费机场
          git diff --quiet && git diff --staged --quiet || git commit -m "更新文件"
          git push
